name: po-cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server<2
  - numpy
  - xarray
  - matplotlib
  - hvplot
  - intake
  - intake-xarray
  - gcsfs
  - dask
  - dask-gateway
  - fsspec
  - holoviews
  - datashader
  - ipyleaflet
  - cartopy
  - pyresample
  - xgcm
  - xhistogram
  - sphinx-pythia-theme
